version: '3'
services:
  # postgres:
  #   image: postgres:9.6
  #   environment:
  #     - POSTGRES_USER=airflow
  #     - POSTGRES_PASSWORD=airflow
  #     - POSTGRES_DB=airflow
  #   ports:
  #     - "5432:5432"

  airflow:
    image: puckel/docker-airflow:1.10.4
    build:
      context: .
      dockerfile: Dockerfile-dev
      # args:
      #   AIRFLOW_DEPS: gcp_api,s3        
    # restart: always
    # depends_on:
    #   - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
      - ./:/opt
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  minio:
    image: minio/minio #:RELEASE.2019-09-18T21-55-05Z
    # volumes:
    #   - data1-1:/data1
    #   - data1-2:/data2
    ports:
      - "9000:9000"
    # networks:
    #   quicksign:
    #     aliases:
    #       - minio

    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


# networks:
#   quicksign:
#     ipam:
#       driver: default
