version: '3'
services:
  # postgres:
  #   image: postgres:9.6
  #   environment:
  #     - POSTGRES_USER=airflow
  #     - POSTGRES_PASSWORD=airflow
  #     - POSTGRES_DB=airflow
  #   ports:
  #     - "5432:5432"

  airflow:
    image: airflow
    build:
      context: .
      dockerfile: Dockerfile-dev        
    # restart: always
    # depends_on:
    #   - mariadb
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    volumes:
      - ../src/:/opt
      - ../src/dags:/root/airflow/dags
    ports:
      - "8080:8080"
    networks:
      quicksign:
        aliases:
          - airflow
    #command: airflow webserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 20s
      retries: 3


  minio:
    image: minio/minio #:RELEASE.2019-09-18T21-55-05Z
    ports:
      - "9001:9000"
    networks:
      quicksign:
        aliases:
          - minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


networks:
  quicksign:
    ipam:
      driver: default
