version: '3'
services:

  airflow:
    image: airflow
    container_name: "airflow"
    build:
      context: .
      dockerfile: Dockerfile-dev        
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - MONGODB_PICSUMDB_NAME=picsum
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    volumes:
      - ../src/:/opt/src
      - ../src/dags:/root/airflow/dags
      - ../tests:/opt/tests
      - ../src/lib:/usr/local/lib/python3.7/site-packages/etlqs
    ports:
      - "8080:8080"
    networks:
      quicksign:
        ipv4_address: 172.28.1.1
        aliases:
          - airflow
    #command: airflow webserver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    image: minio/minio 
    container_name: "minio"
    ports:
      - "9001:9000"
    networks:
      quicksign:
        ipv4_address: 172.28.1.2
        aliases:
          - minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      # MONGODB_USER: "yoyo"
      # MONGODB_DATABASE: "quicksign"
      # MONGODB_PASS: "yoyo123"
      MONGO_DATA_DIR: "/data/db"
    ports:
      - "27017:27017"
    networks:
      quicksign:
        ipv4_address: 172.28.1.3
        aliases:
          - mongodb
    
networks:
  quicksign:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
